version: '3.8'

services:
  db:
    image: postgres
    container_name: currency_db
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112233
    ports:
    - "5438:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: