version: "3.8"
services:
  currency:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_service
    depends_on:
      - db
    environment:
      - CONFIG_PATH=config/config.yaml
    networks:
      - backend

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cron_worker
    depends_on:
      - db
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
        - "8080:8080"
    depends_on:
      - currency
    networks:
      - backend
  db:
    image: postgres
    container_name: currency_db
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112233
    ports:
    - "5438:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend: