server:
  host: "localhost"
  port: 8080

auth:
  url: "http://localhost:8081/validate"

currency-service:
  url: "http://currency-service:50051"

secret_key:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0IiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxMjM0fQ.8oc-KZuuLCNwvkkpX2nFA4-YcDwcg2Y8e-WtvM--KSM"